### ISSUE TITLE
How could i record current teams session with recorder simply from bat

### ISSUE THREAD

**Issue by pcouas** [padiix/RecORDER#24]
Hi,
It seems me recorder python script could help me to launch an obsstudio instance for current MS-TEAMS session on windows10 simply from batch command ?
But how could i make it ?
Regards

**Comment by padiix** [comment]
My script is only organizing recordings based on the title of Window Capture or the Game Capture.

If you need help creating some kind of script that might be useful to you - you can reach out to the good people on Official OBS Discord.
