### ISSUE TITLE
Checksum hasn't been updated for the v1.5.1 release.

### ISSUE THREAD

**Issue by Brandon98SE** [padiix/RecORDER#25]
1.5.1 has an incorrect checksum.
![image](https://github.com/user-attachments/assets/7ba99a11-6252-473f-92df-7ddaae87228f)

**Comment by padiix** [comment]
Good find!
I will update the file as soon as I can get on my PC.

**Comment by padiix** [comment]
Should be fixed now, let me know if you find anything else!

Thanks!

**Comment by Brandon98SE** [comment]
No problem! 
# :3
